import type { Metadata } from "next";
import { Inter,Poppins } from "next/font/google";
import "./globals.css";
import ContextAppProvider from "./Pages/ContextApp";

const inter = Inter({ subsets: ["latin"], });

//I will be using Poppins and Inter for this project. It sets up the main HTML shell for app, defines default metadata, and makes the 'Poppins' font available as a CSS variable (--font-poppins) for you to use in my stylesheet (like globals.css)
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ['100','200','300','400','500','600','700','800','900'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <ContextAppProvider>
          {children}
        </ContextAppProvider>
      </body>
    </html>
  );
}
